services:
  - type: web
    name: slot-checker
    env: python
    buildCommand: ""
    startCommand: python main.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
